name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish Blazor Project
      run: dotnet publish -c Release -o release

    - name: Create 404.html for routing
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Fix base href path
      run: |
        sed -i 's/<base href="\/" \/>/<base href="\/Restaurante_MockUp\/" \/>/g' release/wwwroot/index.html
        sed -i 's/<base href="\/" \/>/<base href="\/Restaurante_MockUp\/" \/>/g' release/wwwroot/404.html

    - name: Deploy to GitHub Pages Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: release/wwwroot